// <auto-generated />
using System;
using BookHistory.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookHistory.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251219152218_AddSeeds")]
    partial class AddSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("BookHistory.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Authors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PublishDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Authors = "[\"J.R.R. Tolkien\"]",
                            Description = "A fantasy novel",
                            PublishDate = new DateOnly(1937, 9, 21),
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Authors = "[\"Frank Herbert\"]",
                            Description = "Science fiction epic",
                            PublishDate = new DateOnly(1965, 8, 1),
                            Title = "Dune"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Authors = "[\"Isaac Asimov\"]",
                            Description = "Sci-fi about the fall of empires",
                            PublishDate = new DateOnly(1951, 6, 1),
                            Title = "Foundation"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Authors = "[\"Robert C. Martin\"]",
                            Description = "A handbook of agile software craftsmanship",
                            PublishDate = new DateOnly(2008, 8, 1),
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Authors = "[\"Andrew Hunt\",\"David Thomas\"]",
                            Description = "Journey to mastery",
                            PublishDate = new DateOnly(1999, 10, 30),
                            Title = "The Pragmatic Programmer"
                        });
                });

            modelBuilder.Entity("BookHistory.Domain.Entities.BookChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("BookChanges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            BookId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ChangeType = "BookCreated",
                            Description = "Book was created",
                            OccurredAt = new DateTime(2020, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            BookId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ChangeType = "BookCreated",
                            Description = "Book was created",
                            OccurredAt = new DateTime(2021, 1, 2, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            BookId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ChangeType = "BookCreated",
                            Description = "Book was created",
                            OccurredAt = new DateTime(2022, 1, 3, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            BookId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ChangeType = "BookCreated",
                            Description = "Book was created",
                            OccurredAt = new DateTime(2024, 1, 4, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            BookId = new Guid("55555555-5555-5555-5555-555555555555"),
                            ChangeType = "BookCreated",
                            Description = "Book was created",
                            OccurredAt = new DateTime(2025, 1, 5, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BookHistory.Domain.Entities.BookChange", b =>
                {
                    b.HasOne("BookHistory.Domain.Entities.Book", "Book")
                        .WithMany("BookChanges")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BookHistory.Domain.Entities.Book", b =>
                {
                    b.Navigation("BookChanges");
                });
#pragma warning restore 612, 618
        }
    }
}
